version: "3"

services:

   django2:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
     - ./userSystem/userSystem/.env
    ports:
      - "9001:9000"
    volumes:
      - static_volume:/app2/static
   nginx:
    image: nginx:latest
    volumes:
      - ./nginx2.http.config:/etc/nginx/nginx.conf
      #- ./assets/nginx/certs:/etc/nginx/certs
      - static_volume:/app2/static
    ports:
       - "101:100"
    depends_on:
      - django2
    restart:
      on-failure:5
volumes:
  static_volume:
